spring:
  application:
    name: E_Notes
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
  profiles:
    active: dev

file:
  upload:
    path: notes/

springdoc:
  api-docs:
    path: /enotes-api-docs
  swagger-ui:
    path: /enotes-doc/
    operationsSorter: method

---

# 🔧 Development profile
spring:
  config:
    activate:
      on-profile: dev
  server:
    port: 8080
  mail:
    username: EMAIL@gmail.com
    password: password
  datasource:
    url: jdbc:mysql://localhost:3306/enotes_dev
    username: root
    password: 09072005
    driver-class-name: com.mysql.cj.jdbc.Driver

---

# 🚀 Production profile
spring:
  config:
    activate:
      on-profile: prod
  server:
    port: 8082
  datasource:
    url: jdbc:mysql://localhost:3306/enotes_prod
    username: root
    password: 09072005
    driver-class-name: com.mysql.cj.jdbc.Driver

---

# 🧪 Test profile
spring:
  config:
    activate:
      on-profile: test
  server:
    port: 8081
  mail:
    username: "[[${email}]]"
    password: "[[${password}]]"
  datasource:
    url: jdbc:mysql://localhost:3306/enotes_test
    username: root
    password: 09072005
    driver-class-name: com.mysql.cj.jdbc.Driver

---

# 🔬 UAT profile
spring:
  config:
    activate:
      on-profile: uat
  server:
    port: 8090
  mail:
    username: "[[${email}]]"
    password: "[[${password}]]"
  datasource:
    url: jdbc:mysql://localhost:3306/enotes_util
    username: root
    password: 09072005
    driver-class-name: com.mysql.cj.jdbc.Driver
