spring:
  application:
    name: E_Notes
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    properties.mail.smtp.auth : true
    properties.mail.smtp.starttls.enable : true


file:
  upload:
    path: notes/


---
# dev
spring:
  mail:
    username: EMAIL@gmail.com
    password: password


  datasource:
    url: mysql://localhost:3306/enotes_dev
    username: root
    password: 09072005
    driver-class-name: com.mysql.cj.jdbc.Driver

---
# prod
spring:
  config:
    activate:
      on-profile: prod


  datasource:
    url: mysql://localhost:3306/enotes_prod
    username: root
    password: 09072005
    driver-class-name: com.mysql.cj.jdbc.Driver

---
# test
spring:
  config:
    activate:
      on-profile: test
  mail:
    username: [[${email}]]
    password: [[${password}]]


  datasource:
    url: mysql://localhost:3306/enotes_test
    username: root
    password: 09072005
    driver-class-name: com.mysql.cj.jdbc.Driver



---
# uat
spring:
  config:
    activate:
      on-profile: uat
  mail:
    username: [[${email}]]
    password: [[${password}]]


  datasource:
    url: mysql://localhost:3306/enotes_util
    username: root
    password: 09072005
    driver-class-name: com.mysql.cj.jdbc.Driver
